### PR TITLE
libflexalloc: small documentation fixups

### PR DESCRIPTION
**Pull request by vincentkfu**
Hey guys, please take a look at this patch that cleans up the documentation in a couple places. Thanks.

Vincent

### CODE REVIEW

**Comment by nmtadam** [comment]
LGTM @Joelgranados take a look and merge

**Comment by nmtadam** [comment]
@jwdevantier take a look as well, I think if we get 2/3 reviews we should merge.

**Review by Joelgranados — APPROVED** [review]
LGTM

**Review by nmtadam — APPROVED** [review]

**Comment by nmtadam** [comment]
Going with a rebase and merge

**Pull request merged**
