### PR TITLE
Jwd/sphinx

### PR DESCRIPTION
**Pull request by jwdevantier**
Introducing a way of building and maintaining documentation.

Uses Sphinx (as xNVME does), though using the PyData theme instead.

Uses Github actions to build the documentation, producing a single-commit branch which GH uses for its pages feature (~> you push, the documentation gets built and gets published at https://openmpdk.github.io/FlexAlloc/ ).

### CODE REVIEW

**Comment by nmtadam** [comment]
Can you sign your commits?

**Review by nmtadam — COMMENTED** [review]
I would squash this onto the previous commit.

**Review by nmtadam — COMMENTED** [review]
I would suggest squashing all changes to conf.py into one commit.

**Review by nmtadam — COMMENTED** [review]
I would consider squashing this commit somewhere as well.

**Comment by nmtadam** [comment]
Once the commits are cleaned up LGTM, cool stuff.

**Review by Joelgranados — COMMENTED** [review]
These commits are just tests : ee0b17e2fb44fbf4484fc57cd6ac02a6b6c0388b, faf53c4b563121f91dab41104f7521d7cf9d3f93, bab20874b29f5d5bbe45a170094a12a4db0690f7
I would just squash them into f6970984de6ceba2dbb5e39ac94c7bd76d753660

**Comment by Joelgranados** [comment]
Commits 89d937bb71b941eb8926ba9d064af4f6a9cadf56, 5d2554bc25ec3b9f60b6517b1bc79a199f10a179, 740a7255e134f3ac8cfac4ed4b206ed889502f44, 326b54ebafb5dd89651bfe9aef3c4801ad5e3444, 54be508213f47af6f316f85f046e5b246a55b31e, d82592810df2ddf08ddd6d1d3148e8f17a8134bb, 0d3f17dda5e133b665b199f2ad17844592ad7321 are all about the same thing and fix only details. I would squash them all into one.

**Comment by Joelgranados** [comment]
For the documentation I would also Prepend "Doc:" to the git commit message.

**Comment by Joelgranados** [comment]
Does this set only cover API documentation? I noticed that https://openmpdk.github.io/FlexAlloc/  only has API specific content.

**Review by Joelgranados — APPROVED** [review]

**Pull request merged**
